# Generated by Django 6.0.4 on 2026-04-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Pothole', 'Hazardous Pothole'), ('Water', 'Major Pipe Burst'), ('Power', 'Grid Failure'), ('Traffic', 'Traffic Light Malfunction')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
